export default function Footer() {
  return (
    <span>
      This project is intended for testing, educational, and placeholder
      purposes. Values generated by this tool are placeholder values based on
      format and are not meant for official or production use. This project is
      licensed under the Apache License 2.0. The tool operates client-side; it
      does not transmit any data to or from servers. For further details, please
      refer to this project`s{" "}
      <a href="https://github.com/lalugue/tfn-validator-generator">
        repository
      </a>
      .
    </span>
  );
}
