export default function Footer() {
  return (
    <span>
      This project is for testing, educational, and placeholder purposes. Values
      generated by this tool are placeholder values based on format. They are
      not meant for official or production use. This tool works client-side; it
      does not transmit any data to or from servers. For further details, please
      check this project`s
      <a href="https://github.com/lalugue/tfn-validator-generator">
        repository
      </a>
      .
    </span>
  );
}
