export default function Footer() {
  return (
    <span>
      This project is for testing, educational, and placeholder purposes. Values
      generated by this tool are placeholder values and should not be used for
      official purposes.
    </span>
  );
}
